name: nuget package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build
      run: dotnet build -c Release
    - name: Pack
      run: dotnet pack -c Release --no-build --output .
    - name: Push
      run: dotnet nuget push "*.nupkg" --api-key ${secrets.KEY} --source https://nuget.pkg.github.com/dsniels/index.json



